version: 2

sources:
  - name: grubhub
    database: analytics_dev
    schema: bdc_lisa
    tables:
      - name: orders
      - name: order_items
      - name: restaurants

  - name: open_data
    database: analytics_dev
    schema: bdc_lisa
    tables:
      - name: pokemon 
