eating:
  outputs:
    dev:
      account: brooklyndatapartner
      authenticator: externalbrowser
      database: ANALYTICS_DEV
      schema: BDC_LISA
      threads: 1
      type: snowflake
      user: lisa.fang@brooklyndata.co
      warehouse: DEVELOPER
      client_session_keep_alive: true
      reuse_connection: true
  target: dev
